relators_by_name = {
    "abridger": "abr",
    "art copyist": "acp",
    "actor": "act",
    "art director": "adi",
    "adapter": "adp",
    "author of afterword, colophon, etc.": "aft",
    "author of afterword, colophon": "aft",
    "analyst": "anl",
    "animator": "anm",
    "annotator": "ann",
    "bibliographic antecedent": "ant",
    "appellee": "ape",
    "appellant": "apl",
    "applicant": "app",
    "author in quotations or text abstracts": "aqt",
    "architect": "arc",
    "artistic director": "ard",
    "arranger": "arr",
    "artist": "art",
    "assignee": "asg",
    "associated name": "asn",
    "autographer": "ato",
    "attributed name": "att",
    "auctioneer": "auc",
    "author of dialog": "aud",
    "author of introduction, etc.": "aui",
    "author of introduction": "aui",
    "screenwriter": "aus",
    "author": "aut",
    "binding designer": "bdd",
    "bookjacket designer": "bjd",
    "book designer": "bkd",
    "book producer": "bkp",
    "blurb writer": "blw",
    "binder": "bnd",
    "bookplate designer": "bpd",
    "broadcaster": "brd",
    "braille embosser": "brl",
    "bookseller": "bsl",
    "caster": "cas",
    "conceptor": "ccp",
    "choreographer": "chr",
    "collaborator": "clb",
    "client": "cli",
    "calligrapher": "cll",
    "colorist": "clr",
    "collotyper": "clt",
    "commentator": "cmm",
    "composer": "cmp",
    "compositor": "cmt",
    "conductor": "cnd",
    "cinematographer": "cng",
    "censor": "cns",
    "contestant-appellee": "coe",
    "collector": "col",
    "compiler": "com",
    "conservator": "con",
    "collection registrar": "cor",
    "contestant": "cos",
    "contestant-appellant": "cot",
    "court governed": "cou",
    "cover designer": "cov",
    "copyright claimant": "cpc",
    "complainant-appellee": "cpe",
    "copyright holder": "cph",
    "complainant": "cpl",
    "complainant-appellant": "cpt",
    "creator": "cre",
    "correspondent": "crp",
    "corrector": "crr",
    "court reporter": "crt",
    "consultant": "csl",
    "consultant to a project": "csp",
    "costume designer": "cst",
    "contributor": "ctb",
    "contestee-appellee": "cte",
    "cartographer": "ctg",
    "contractor": "ctr",
    "contestee": "cts",
    "contestee-appellant": "ctt",
    "curator": "cur",
    "commentator for written text": "cwt",
    "distribution place": "dbp",
    "defendant": "dfd",
    "defendant-appellee": "dfe",
    "defendant-appellant": "dft",
    "degree granting institution": "dgg",
    "degree supervisor": "dgs",
    "dissertant": "dis",
    "delineator": "dln",
    "dancer": "dnc",
    "donor": "dnr",
    "depicted": "dpc",
    "depositor": "dpt",
    "draftsman": "drm",
    "director": "drt",
    "designer": "dsr",
    "distributor": "dst",
    "data contributor": "dtc",
    "dedicatee": "dte",
    "data manager": "dtm",
    "dedicator": "dto",
    "dubious author": "dub",
    "editor of compilation": "edc",
    "editor of moving image work": "edm",
    "editor": "edt",
    "engraver": "egr",
    "electrician": "elg",
    "electrotyper": "elt",
    "engineer": "eng",
    "enacting jurisdiction": "enj",
    "etcher": "etr",
    "event place": "evp",
    "expert": "exp",
    "facsimilist": "fac",
    "film distributor": "fds",
    "field director": "fld",
    "film editor": "flm",
    "film director": "fmd",
    "filmmaker": "fmk",
    "former owner": "fmo",
    "film producer": "fmp",
    "funder": "fnd",
    "first party": "fpy",
    "forger": "frg",
    "geographic information specialist": "gis",
    "graphic technician": "grt",
    "host institution": "his",
    "honoree": "hnr",
    "honouree": "hnr",  # not correct, but happens
    "host": "hst",
    "illustrator": "ill",
    "illuminator": "ilu",
    "inscriber": "ins",
    "inventor": "inv",
    "issuing body": "isb",
    "instrumentalist": "itr",
    "interviewee": "ive",
    "interviewer": "ivr",
    "judge": "jud",
    "jurisdiction governed": "jug",
    "laboratory": "lbr",
    "librettist": "lbt",
    "laboratory director": "ldr",
    "lead": "led",
    "libelee-appellee": "lee",
    "libelee": "lel",
    "lender": "len",
    "libelee-appellant": "let",
    "lighting designer": "lgd",
    "libelant-appellee": "lie",
    "libelant": "lil",
    "libelant-appellant": "lit",
    "landscape architect": "lsa",
    "licensee": "lse",
    "licensor": "lso",
    "lithographer": "ltg",
    "lyricist": "lyr",
    "music copyist": "mcp",
    "metadata contact": "mdc",
    "medium": "med",
    "manufacture place": "mfp",
    "manufacturer": "mfr",
    "moderator": "mod",
    "monitor": "mon",
    "marbler": "mrb",
    "markup editor": "mrk",
    "musical director": "msd",
    "metal-engraver": "mte",
    "minute taker": "mtk",
    "musician": "mus",
    "narrator": "nrt",
    "opponent": "opn",
    "originator": "org",
    "organizer": "orm",
    "onscreen presenter": "osp",
    "other": "oth",
    "owner": "own",
    "panelist": "pan",
    "patron": "pat",
    "publishing director": "pbd",
    "publisher": "pbl",
    "project director": "pdr",
    "proofreader": "pfr",
    "photographer": "pht",
    "platemaker": "plt",
    "permitting agency": "pma",
    "production manager": "pmn",
    "printer of plates": "pop",
    "papermaker": "ppm",
    "puppeteer": "ppt",
    "praeses": "pra",
    "process contact": "prc",
    "production personnel": "prd",
    "presenter": "pre",
    "performer": "prf",
    "programmer": "prg",
    "printmaker": "prm",
    "production company": "prn",
    "producer": "pro",
    "production place": "prp",
    "production designer": "prs",
    "printer": "prt",
    "provider": "prv",
    "patent applicant": "pta",
    "plaintiff-appellee": "pte",
    "plaintiff": "ptf",
    "patent holder": "pth",
    "plaintiff-appellant": "ptt",
    "publication place": "pup",
    "rubricator": "rbr",
    "recordist": "rcd",
    "recording engineer": "rce",
    "addressee": "rcp",
    "radio director": "rdd",
    "redaktor": "red",
    "renderer": "ren",
    "researcher": "res",
    "reviewer": "rev",
    "radio producer": "rpc",
    "repository": "rps",
    "reporter": "rpt",
    "responsible party": "rpy",
    "respondent-appellee": "rse",
    "restager": "rsg",
    "respondent": "rsp",
    "restorationist": "rsr",
    "respondent-appellant": "rst",
    "research team head": "rth",
    "research team member": "rtm",
    "scientific advisor": "sad",
    "scenarist": "sce",
    "sculptor": "scl",
    "scribe": "scr",
    "sound designer": "sds",
    "secretary": "sec",
    "stage director": "sgd",
    "signer": "sgn",
    "supporting host": "sht",
    "seller": "sll",
    "singer": "sng",
    "speaker": "spk",
    "sponsor": "spn",
    "sponsoring body": "spn",
    "second party": "spy",
    "surveyor": "srv",
    "set designer": "std",
    "setting": "stg",
    "storyteller": "stl",
    "stage manager": "stm",
    "standards body": "stn",
    "stereotyper": "str",
    "technical director": "tcd",
    "teacher": "tch",
    "thesis advisor": "ths",
    "television director": "tld",
    "television producer": "tlp",
    "transcriber": "trc",
    "translator": "trl",
    "type designer": "tyd",
    "typographer": "tyg",
    "university place": "uvp",
    "voice actor": "vac",
    "videographer": "vdg",
    "vocalist": "voc",
    "writer of added commentary": "wac",
    "writer of added lyrics": "wal",
    "writer of accompanying material": "wam",
    "writer of added text": "wat",
    "woodcutter": "wdc",
    "wood engraver": "wde",
    "writer of introduction": "win",
    "witness": "wit",
    "writer of preface": "wpr",
    "writer of foreword": "wpr",  # not correct, but occurring in data
    "writer of supplementary textual content": "wst",
    "writer of afterword": "wst",  # not correct, but occurring in data
    "co-author": "aut",  # not correct, but occurring in data
    "edited by": "edt",  # not correct, but occurring in data
    "hrsg": "edt",  # not correct, but occurring in data
    "verlag": "pbl",  # not correct, but occurring in data
    "verfasser": "aut",  # not correct, but occurring in data
    "mitwirkender": "ctb",  # not correct, but occurring in data
    "herausgeber": "edt",  # not correct, but occurring in data
    "sonstige": "oth",  # not correct, but occurring in data
    "verfasser eines geleitworts": "wst"  # not correct, but occurring in data
}

country_codes_marc2iso = {
    "an": "XA-AD",
    "ts": "XB-AE",
    "af": "XB-AF",
    "aq": "XD-AG",
    "am": "XD-AI",
    "aa": "XA-AL",
    "ai": "XB-AM",
    "na": "XD-AN",
    "ao": "XC-AO",
    "ay": "XI-AQ",
    "ag": "XD-AR",
    "as": "XD-AS",
    "au": "XA-AT",
    "at": "XE-AU",
    "aw": "XD-AW",
    "fi": "XA-AX",
    "aj": "XB-AZ",
    "bn": "XA-BA",
    "bb": "XD-BB",
    "bg": "XB-BD",
    "be": "XA-BE",
    "uv": "XC-BF",
    "bu": "XA-BG",
    "ba": "XB-BH",
    "bd": "XC-BI",
    "dm": "XC-BJ",
    "gp": "XD-BL",
    "bm": "XD-BM",
    "bx": "XB-BN",
    "bo": "XD-BO",
    "bl": "XD-BR",
    "bf": "XD-BS",
    "bt": "XB-BT",
    "bv": "XK-BV",
    "bs": "XC-BW",
    "bw": "XA-BY",
    "bh": "XD-BZ",
    "xxc": "XD-CA",
    "abc": "XD-CA-AB",
    "bcc": "XD-CA-BC",
    "mbc": "XD-CA-MB",
    "nkc": "XD-CA-NB",
    "nfc": "XD-CA-NL",
    "ntc": "XD-CA-NT",
    "nsc": "XD-CA-NS",
    "nuc": "XD-CA-NU",
    "onc": "XD-CA-ON",
    "pic": "XD-CA-PE",
    "quc": "XD-CA-QC",
    "snc": "XD-CA-SK",
    "ykc": "XD-CA-YT",
    "xb": "XE-CC",
    "cg": "XC-CD",
    "cx": "XC-CF",
    "cf": "XC-CG",
    "sz": "XA-CH",
    "iv": "XC-CI",
    "cw": "XE-CK",
    "cl": "XD-CL",
    "cm": "XC-CM",
    "cc": "XB-CN",
    "ck": "XD-CO",
    "cr": "XD-CR",
    "cu": "XD-CU",
    "cv": "XC-CV",
    "xa": "XE-CX",
    "cy": "XA-CY",
    "xr": "XA-CZ",
    "gw": "XA-DE",
    "ft": "XC-DJ",
    "dk": "XA-DK",
    "dq": "XD-DM",
    "dr": "XD-DO",
    "ae": "XC-DZ",
    "ec": "XD-EC",
    "er": "XA-EE",
    "ua": "XC-EG",
    "ss": "XC-EH",
    "ea": "XC-ER",
    "sp": "XA-ES",
    "et": "XC-ET",
    "fi": "XA-FI",
    "fj": "XE-FJ",
    "fk": "XK-FK",
    "fm": "XE-FM",
    "fa": "XK-FO",
    "fr": "XA-FR",
    "go": "XC-GA",
    "xxk": "XA-GB",
    "enk": "XA-GB-ENG",
    "nik": "XA-GB-NIR",
    "stk": "XA-GB-SCT",
    "uik": "XA-GB",
    "wlk": "XA-GB-WLS",
    "gd": "XD-GD",
    "gs": "XB-GE",
    "fg": "XD-GF",
    "gg": "XA-GG",
    "gh": "XC-GH",
    "gi": "XA-GI",
    "gl": "XK-GL",
    "gm": "XC-GM",
    "gv": "XC-GN",
    "gp": "XD-GP",
    "eg": "XC-GQ",
    "gr": "XA-GR",
    "xs": "XK-GS",
    "gt": "XD-GT",
    "gu": "XE-GU",
    "pg": "XC-GW",
    "gy": "XD-GY",
    "cc": "XB-HK",
    "hm": "XI-HM",
    "ho": "XD-HN",
    "ci": "XA-HR",
    "ht": "XD-HT",
    "hu": "XA-HU",
    "io": "XB-ID",
    "ie": "XA-IE",
    "is": "XB-IL",
    "uik": "XA-IM",
    "ii": "XB-IN",
    "bi": "XL-IO",
    "iq": "XB-IQ",
    "ir": "XB-IR",
    "ic": "XA-IS",
    "it": "XA-IT",
    "uik": "XA-JE",
    "jm": "XD-JM",
    "jo": "XB-JO",
    "ja": "XB-JP",
    "ke": "XC-KE",
    "kg": "XB-KG",
    "cb": "XB-KH",
    "gb": "XE-KI",
    "cq": "XC-KM",
    "xd": "XD-KN",
    "kn": "XB-KP",
    "ko": "XB-KR",
    "ku": "XB-KW",
    "cj": "XD-KY",
    "kz": "XB-KZ",
    "ls": "XB-LA",
    "le": "XB-LB",
    "xk": "XD-LC",
    "lh": "XA-LI",
    "ce": "XB-LK",
    "lb": "XC-LR",
    "lo": "XC-LS",
    "li": "XA-LT",
    "lu": "XA-LU",
    "lv": "XA-LV",
    "ly": "XC-LY",
    "mr": "XC-MA",
    "mc": "XA-MC",
    "mv": "XA-MD",
    "yu": "XA-ME",
    "gp": "XD-MF",
    "mg": "XC-MG",
    "xe": "XE-MH",
    "xn": "XA-MK",
    "ml": "XC-ML",
    "br": "XB-MM",
    "mp": "XB-MN",
    "cc": "XB-MO",
    "nw": "XE-MP",
    "mq": "XD-MQ",
    "mu": "XC-MR",
    "mj": "XD-MS",
    "mm": "XA-MT",
    "mf": "XC-MU",
    "xc": "XB-MV",
    "mw": "XC-MW",
    "mx": "XD-MX",
    "my": "XB-MY",
    "mz": "XC-MZ",
    "sx": "XC-NA",
    "nl": "XE-NC",
    "ng": "XC-NE",
    "nx": "XE-NF",
    "nr": "XC-NG",
    "nq": "XD-NI",
    "ne": "XA-NL",
    "no": "XA-NO",
    "np": "XB-NP",
    "nu": "XE-NR",
    "xh": "XM-NU",
    "nz": "XE-NZ",
    "mk": "XB-OM",
    "pn": "XD-PA",
    "pe": "XD-PE",
    "fp": "XE-PF",
    "pp": "XE-PG",
    "ph": "XB-PH",
    "pk": "XB-PK",
    "pl": "XA-PL",
    "xl": "XD-PM",
    "pc": "XM-PN",
    "pr": "XD-PR",
    "po": "XA-PT",
    "pw": "XE-PW",
    "py": "XD-PY",
    "qa": "XB-QA",
    "re": "XL-RE",
    "rm": "XA-RO",
    "yu": "XA-RS",
    "ru": "XA-RU",
    "rw": "XC-RW",
    "su": "XB-SA",
    "bp": "XE-SB",
    "se": "XC-SC",
    "sj": "XC-SD",
    "sw": "XA-SE",
    "si": "XB-SG",
    "xj": "XK-SH",
    "xv": "XA-SI",
    "no": "XK-SJ",
    "xo": "XA-SK",
    "sl": "XC-SL",
    "sm": "XA-SM",
    "sg": "XC-SN",
    "so": "XC-SO",
    "sr": "XD-SR",
    "sf": "XC-ST",
    "es": "XD-SV",
    "sy": "XB-SY",
    "sq": "XC-SZ",
    "tc": "XD-TC",
    "cd": "XC-TD",
    "fs": "XL-TF",
    "tg": "XC-TG",
    "th": "XB-TH",
    "ta": "XB-TJ",
    "tl": "XE-TK",
    "em": "XB-TL",
    "tk": "XB-TM",
    "ti": "XC-TN",
    "to": "XE-TO",
    "tu": "XB-TR",
    "tr": "XD-TT",
    "tv": "XE-TV",
    "cc": "XB-TW",
    "tz": "XC-TZ",
    "un": "XA-UA",
    "ug": "XC-UG",
    "up": "XM-UM",
    "xxu": "XD-US",
    "alu": "XD-US-AL",
    "aku": "XD-US-AK",
    "azu": "XD-US-AZ",
    "aru": "XD-US-AR",
    "cau": "XD-US-CA",
    "cou": "XD-US-CO",
    "ctu": "XD-US-CT",
    "deu": "XD-US-DE",
    "dcu": "XD-US-DC",
    "flu": "XD-US-FL",
    "gau": "XD-US-GA",
    "hiu": "XD-US-HI",
    "idu": "XD-US-ID",
    "ilu": "XD-US-IL",
    "inu": "XD-US-IN",
    "iau": "XD-US-IA",
    "ksu": "XD-US-KS",
    "kyu": "XD-US-KY",
    "lau": "XD-US-LA",
    "meu": "XD-US-ME",
    "mdu": "XD-US-MD",
    "mau": "XD-US-MA",
    "miu": "XD-US-MI",
    "mnu": "XD-US-MN",
    "msu": "XD-US-MS",
    "mou": "XD-US-MO",
    "mtu": "XD-US-MT",
    "nbu": "XD-US-NE",
    "nvu": "XD-US-NV",
    "nhu": "XD-US-NH",
    "nju": "XD-US-NJ",
    "nmu": "XD-US-NM",
    "nyu": "XD-US-NY",
    "ncu": "XD-US-NC",
    "ndu": "XD-US-ND",
    "ohu": "XD-US-OH",
    "oku": "XD-US-OK",
    "oru": "XD-US-OR",
    "pau": "XD-US-PA",
    "riu": "XD-US-RI",
    "scu": "XD-US-SC",
    "sdu": "XD-US-SD",
    "tnu": "XD-US-TN",
    "txu": "XD-US-TX",
    "utu": "XD-US-UT",
    "vtu": "XD-US-VT",
    "vau": "XD-US-VA",
    "wau": "XD-US-WA",
    "wvu": "XD-US-WV",
    "wiu": "XD-US-WI",
    "wyu": "XD-US-WY",
    "uy": "XD-UY",
    "uz": "XB-UZ",
    "vc": "XA-VA",
    "xm": "XD-VC",
    "ve": "XD-VE",
    "vb": "XD-VG",
    "vi": "XD-VI",
    "vm": "XB-VN",
    "nn": "XE-VU",
    "wf": "XE-WF",
    "ws": "XE-WS",
    "ye": "XB-YE",
    "ot": "XC-YT",
    "sa": "XC-ZA",
    "za": "XC-ZM",
    "rh": "XC-ZW",
}

illustration_terms = {
    "illustrations": "Illustrationen",
    "tables": None,
    "map": "Karte",
    "maps": "Karten",
    "graphs": "Diagramme",
    "photographs": "Illustrationen",
    "illustrations (some color)": "Illustrationen",
    "music": "Notenbeispiele",
    "charts": "Diagramme",
    "color illustrations": "Illustrationen",
    "colour illustrations": "Illustrationen",
    "portraits": "Illustrationen",
    "color portraits": "Illustrationen",
    "chart": "Diagramm",
    "graph": "Diagramm",
    "color map": "Karte",
    "illustrations (chiefly color)": "Illustrationen",
    "illustrations (color)": "Illustrationen",
    "portrait": "Illustration",
    "genealogical tables": "genealogische Tafeln",
    "illustrations (black and white)": "Illustrationen",
    "facsimiles": "Faksimiles",
    "maps (some color)": "Karten",
    "color photographs": "Illustrationen",
    "plan": "Pläne",
    "table": None,
    "maps ": "Karten",
    "musics": "Notenbeispiele",
    "diagrams": "Diagramme",
    "geanological tables": "genealogische Tafeln",
    "color maps": "Karten",
}

articles = (
    # German
    "Das",
    "Dem",
    "Den",
    "Der",
    "Des",
    "Die",
    "Ein",
    "Eine",
    "Einem",
    "Einen",
    "Einer",
    "Eines",
    # English
    "A",
    "An",
    "D'",
    "De",
    "The",
    "Ye")
