relators_by_name = {
"abridger": "abr",
"art copyist": "acp",
"actor": "act",
"art director": "adi",
"adapter": "adp",
"author of afterword, colophon, etc.": "aft",
"analyst": "anl",
"animator": "anm",
"annotator": "ann",
"bibliographic antecedent": "ant",
"appellee": "ape",
"appellant": "apl",
"applicant": "app",
"author in quotations or text abstracts": "aqt",
"architect": "arc",
"artistic director": "ard",
"arranger": "arr",
"artist": "art",
"assignee": "asg",
"associated name": "asn",
"autographer": "ato",
"attributed name": "att",
"auctioneer": "auc",
"author of dialog": "aud",
"author of introduction, etc.": "aui",
"screenwriter": "aus",
"author": "aut",
"binding designer": "bdd",
"bookjacket designer": "bjd",
"book designer": "bkd",
"book producer": "bkp",
"blurb writer": "blw",
"binder": "bnd",
"bookplate designer": "bpd",
"broadcaster": "brd",
"braille embosser": "brl",
"bookseller": "bsl",
"caster": "cas",
"conceptor": "ccp",
"choreographer": "chr",
"collaborator": "clb",
"client": "cli",
"calligrapher": "cll",
"colorist": "clr",
"collotyper": "clt",
"commentator": "cmm",
"composer": "cmp",
"compositor": "cmt",
"conductor": "cnd",
"cinematographer": "cng",
"censor": "cns",
"contestant-appellee": "coe",
"collector": "col",
"compiler": "com",
"conservator": "con",
"collection registrar": "cor",
"contestant": "cos",
"contestant-appellant": "cot",
"court governed": "cou",
"cover designer": "cov",
"copyright claimant": "cpc",
"complainant-appellee": "cpe",
"copyright holder": "cph",
"complainant": "cpl",
"complainant-appellant": "cpt",
"creator": "cre",
"correspondent": "crp",
"corrector": "crr",
"court reporter": "crt",
"consultant": "csl",
"consultant to a project": "csp",
"costume designer": "cst",
"contributor": "ctb",
"contestee-appellee": "cte",
"cartographer": "ctg",
"contractor": "ctr",
"contestee": "cts",
"contestee-appellant": "ctt",
"curator": "cur",
"commentator for written text": "cwt",
"distribution place": "dbp",
"defendant": "dfd",
"defendant-appellee": "dfe",
"defendant-appellant": "dft",
"degree granting institution": "dgg",
"degree supervisor": "dgs",
"dissertant": "dis",
"delineator": "dln",
"dancer": "dnc",
"donor": "dnr",
"depicted": "dpc",
"depositor": "dpt",
"draftsman": "drm",
"director": "drt",
"designer": "dsr",
"distributor": "dst",
"data contributor": "dtc",
"dedicatee": "dte",
"data manager": "dtm",
"dedicator": "dto",
"dubious author": "dub",
"editor of compilation": "edc",
"editor of moving image work": "edm",
"editor": "edt",
"engraver": "egr",
"electrician": "elg",
"electrotyper": "elt",
"engineer": "eng",
"enacting jurisdiction": "enj",
"etcher": "etr",
"event place": "evp",
"expert": "exp",
"facsimilist": "fac",
"film distributor": "fds",
"field director": "fld",
"film editor": "flm",
"film director": "fmd",
"filmmaker": "fmk",
"former owner": "fmo",
"film producer": "fmp",
"funder": "fnd",
"first party": "fpy",
"forger": "frg",
"geographic information specialist": "gis",
"graphic technician": "grt",
"host institution": "his",
"honoree": "hnr",
"honouree": "hnr", # not correct, but happens
"host": "hst",
"illustrator": "ill",
"illuminator": "ilu",
"inscriber": "ins",
"inventor": "inv",
"issuing body": "isb",
"instrumentalist": "itr",
"interviewee": "ive",
"interviewer": "ivr",
"judge": "jud",
"jurisdiction governed": "jug",
"laboratory": "lbr",
"librettist": "lbt",
"laboratory director": "ldr",
"lead": "led",
"libelee-appellee": "lee",
"libelee": "lel",
"lender": "len",
"libelee-appellant": "let",
"lighting designer": "lgd",
"libelant-appellee": "lie",
"libelant": "lil",
"libelant-appellant": "lit",
"landscape architect": "lsa",
"licensee": "lse",
"licensor": "lso",
"lithographer": "ltg",
"lyricist": "lyr",
"music copyist": "mcp",
"metadata contact": "mdc",
"medium": "med",
"manufacture place": "mfp",
"manufacturer": "mfr",
"moderator": "mod",
"monitor": "mon",
"marbler": "mrb",
"markup editor": "mrk",
"musical director": "msd",
"metal-engraver": "mte",
"minute taker": "mtk",
"musician": "mus",
"narrator": "nrt",
"opponent": "opn",
"originator": "org",
"organizer": "orm",
"onscreen presenter": "osp",
"other": "oth",
"owner": "own",
"panelist": "pan",
"patron": "pat",
"publishing director": "pbd",
"publisher": "pbl",
"project director": "pdr",
"proofreader": "pfr",
"photographer": "pht",
"platemaker": "plt",
"permitting agency": "pma",
"production manager": "pmn",
"printer of plates": "pop",
"papermaker": "ppm",
"puppeteer": "ppt",
"praeses": "pra",
"process contact": "prc",
"production personnel": "prd",
"presenter": "pre",
"performer": "prf",
"programmer": "prg",
"printmaker": "prm",
"production company": "prn",
"producer": "pro",
"production place": "prp",
"production designer": "prs",
"printer": "prt",
"provider": "prv",
"patent applicant": "pta",
"plaintiff-appellee": "pte",
"plaintiff": "ptf",
"patent holder": "pth",
"plaintiff-appellant": "ptt",
"publication place": "pup",
"rubricator": "rbr",
"recordist": "rcd",
"recording engineer": "rce",
"addressee": "rcp",
"radio director": "rdd",
"redaktor": "red",
"renderer": "ren",
"researcher": "res",
"reviewer": "rev",
"radio producer": "rpc",
"repository": "rps",
"reporter": "rpt",
"responsible party": "rpy",
"respondent-appellee": "rse",
"restager": "rsg",
"respondent": "rsp",
"restorationist": "rsr",
"respondent-appellant": "rst",
"research team head": "rth",
"research team member": "rtm",
"scientific advisor": "sad",
"scenarist": "sce",
"sculptor": "scl",
"scribe": "scr",
"sound designer": "sds",
"secretary": "sec",
"stage director": "sgd",
"signer": "sgn",
"supporting host": "sht",
"seller": "sll",
"singer": "sng",
"speaker": "spk",
"sponsor": "spn",
"second party": "spy",
"surveyor": "srv",
"set designer": "std",
"setting": "stg",
"storyteller": "stl",
"stage manager": "stm",
"standards body": "stn",
"stereotyper": "str",
"technical director": "tcd",
"teacher": "tch",
"thesis advisor": "ths",
"television director": "tld",
"television producer": "tlp",
"transcriber": "trc",
"translator": "trl",
"type designer": "tyd",
"typographer": "tyg",
"university place": "uvp",
"voice actor": "vac",
"videographer": "vdg",
"vocalist": "voc",
"writer of added commentary": "wac",
"writer of added lyrics": "wal",
"writer of accompanying material": "wam",
"writer of added text": "wat",
"woodcutter": "wdc",
"wood engraver": "wde",
"writer of introduction": "win",
"witness": "wit",
"writer of preface": "wpr",
"writer of foreword": "wpr", # not correct, but occurring in data
"writer of supplementary textual content": "wst",
"writer of afterword": "wst", # not correct, but occurring in data
"co-author": "aut" # not correct, but occurring in data
}

country_codes_marc2iso = {
    "ua": "XC-EG",
    "eg": "XC-GQ",
    "et": "XC-ET",
    "af": "XB-AF",
    "aa": "XA-AL",
    "ae": "XC-DZ",
    "as": "XD-AS",
    "an": "XA-AD",
    "ao": "XC-AO",
    "aq": "XD-AG",
    "ag": "XD-AR",
    "ai": "XB-AM",
    "aj": "XB-AZ",
    "at": "XE-AU",
    "bf": "XD-BS",
    "ba": "XB-BH",
    "bg": "XB-BD",
    "bb": "XD-BB",
    "be": "XA-BE",
    "bh": "XD-BZ",
    "dm": "XC-BJ",
    "bm": "XD-BM",
    "bt": "XB-BT",
    "br": "XB-MM",
    "bo": "XD-BO",
    "bn": "XA-BA",
    "bs": "XC-BW",
    "bl": "XD-BR",
    "bx": "XB-BN",
    "bu": "XA-BG",
    "gw": "XA-DE",
    "uv": "XC-BF",
    "bd": "XC-BI",
    "cj": "XD-KY",
    "cl": "XD-CL",
    "cc": "XB-CN",
    "cr": "XD-CR",
    "dk": "XA-DK",
    "dq": "XD-DM",
    "dr": "XD-DO",
    "ft": "XC-DJ",
    "ec": "XD-EC",
    "es": "XD-SV",
    "iv": "XC-CI",
    "ea": "XC-ER",
    "er": "XA-EE",
    "fa": "XA-FO",
    "fk": "XD-FK",
    "fj": "XE-FJ",
    "fi": "XA-FI",
    "fr": "XA-FR",
    "fg": "XD-GF",
    "fp": "XE-PF",
    "go": "XC-GA",
    "gm": "XC-GM",
    "gs": "XB-GE",
    "gh": "XC-GH",
    "gi": "XA-GI",
    "gd": "XD-GD",
    "gr": "XA-GR",
    "gl": "XK-GL",
    "xxk": "XA-GB",
    "gp": "XD-GP",
    "gu": "XE-GU",
    "gt": "XD-GT",
    "gv": "XC-GN",
    "pg": "XC-GW",
    "gy": "XD-GY",
    "ht": "XD-HT",
    "ho": "XD-HN",
    "ii": "XB-IN",
    "io": "XB-ID",
    "iq": "XB-IQ",
    "ir": "XB-IR",
    "ie": "XA-IE",
    "ic": "XA-IS",
    "is": "XB-IL",
    "it": "XA-IT",
    "jm": "XD-JM",
    "ja": "XB-JP",
    "ye": "XB-YE",
    "jo": "XB-JO",
    "vb": "XD-VG",
    "vi": "XD-VI",
    "cb": "XB-KH",
    "cm": "XC-CM",
    "xxc": "XD-CA",
    "cv": "XC-CV",
    "kz": "XB-KZ",
    "qa": "XB-QA",
    "ke": "XC-KE",
    "kg": "XB-KG",
    "xb": "XE-CC",
    "ck": "XD-CO",
    "cg": "XC-CD",
    "cf": "XC-CG",
    "ci": "XA-HR",
    "cu": "XD-CU",
    "ku": "XB-KW",
    "ls": "XB-LA",
    "lo": "XC-LS",
    "lv": "XA-LV",
    "le": "XB-LB",
    "lb": "XC-LR",
    "ly": "XC-LY",
    "lh": "XA-LI",
    "li": "XA-LT",
    "lu": "XA-LU",
    "mg": "XC-MG",
    "xn": "XA-MK",
    "mw": "XC-MW",
    "my": "XB-MY",
    "xc": "XB-MV",
    "ml": "XC-ML",
    "mm": "XA-MT",
    "mr": "XC-MA",
    "mq": "XD-MQ",
    "mu": "XC-MR",
    "mf": "XC-MU",
    "mx": "XD-MX",
    "mz": "XC-MZ",
    "mv": "XA-MD",
    "mc": "XA-MC",
    "mp": "XB-MN",
    "mo": "XA-ME",
    "mj": "XD-MS",
    "sx": "XC-NA",
    "np": "XB-NP",
    "nl": "XE-NC",
    "nz": "XE-NZ",
    "nq": "XD-NI",
    "ne": "XA-NL",
    "ng": "XC-NE",
    "nr": "XC-NG",
    "kn": "XB-KP",
    "nx": "XE-NF",
    "no": "XA-NO",
    "au": "XA-AAAT",
    "mk": "XB-OM",
    "pk": "XB-PK",
    "pn": "XD-PA",
    "pp": "XE-PG",
    "py": "XD-PY",
    "pe": "XD-PE",
    "ph": "XB-PH",
    "pl": "XA-PL",
    "po": "XA-PT",
    "pr": "XD-PR",
    "re": "XL-RE",
    "rm": "XA-RO",
    "ru": "XA-RU",
    "rw": "XC-RW",
    "xk": "XD-LC",
    "xm": "XD-VC",
    "bp": "XE-SB",
    "za": "XC-ZM",
    "sm": "XA-SM",
    "xj": "XA-CSHH",
    "su": "XB-SA",
    "sw": "XA-SE",
    "sz": "XA-CH",
    "sg": "XC-SN",
    "rb": "XA-RS",
    "se": "XC-SC",
    "sl": "XC-SL",
    "rh": "XC-ZW",
    "si": "XB-SG",
    "xo": "XA-SK",
    "xv": "XA-SI",
    "so": "XC-SO",
    "sp": "XA-ES",
    "ce": "XB-LK",
    "sj": "XC-SD",
    "sa": "XC-ZA",
    "ko": "XB-KR",
    "sr": "XD-SR",
    "sq": "XC-SZ",
    "sy": "XB-SY",
    "ta": "XB-TJ",
    "ch": "XB-TW",
    "tz": "XC-TZ",
    "th": "XB-TH",
    "tg": "XC-TG",
    "tl": "XE-TK",
    "to": "XE-TO",
    "tr": "XD-TT",
    "cd": "XC-TD",
    "xr": "XA-CZ",
    "tu": "XB-TR",
    "ti": "XC-TN",
    "tk": "XB-TM",
    "tv": "XE-TV",
    "xxu": "XD-US",
    "ug": "XC-UG",
    "un": "XA-UA",
    "hu": "XA-HU",
    "uy": "XD-UY",
    "uz": "XB-UZ",
    "vc": "XA-VA",
    "ve": "XD-VE",
    "ts": "XB-AE",
    "vm": "XB-VN",
    "bw": "XA-BY",
    "ss": "XC-EH",
    "ws": "XE-WS",
    "cx": "XC-CF",
    "cy": "XA-CY",
    "sn": "XA-CSXX",
}

illustration_terms = {
    "illustrations": "Illustrationen",
    "tables": None,
    "map": "Karte",
    "maps": "Karten",
    "graphs": "Diagramme",
    "photographs": "Illustrationen",
    "illustrations (some color)": "Illustrationen",
    "music": "Notenbeispiele",
    "charts": "Diagramme",
    "color illustrations": "Illustrationen",
    "colour illustrations": "Illustrationen",
    "portraits": "Illustrationen",
    "color portraits": "Illustrationen",
    "chart": "Diagramm",
    "graph": "Diagramm",
    "color map": "Karte",
    "illustrations (chiefly color)": "Illustrationen",
    "illustrations (color)": "Illustrationen",
    "portrait": "Illustration",
    "genealogical tables": "genealogische Tafeln",
    "illustrations (black and white)": "Illustrationen",
    "facsimiles": "Faksimiles",
    "maps (some color)": "Karten",
    "color photographs": "Illustrationen",
    "plan": "Pläne",
    "table": None,
    "maps ": "Karten",
    "musics": "Notenbeispiele",
    "diagrams": "Diagramme",
    "geanological tables": "genealogische Tafeln",
    "color maps": "Karten",
}
